### PR TITLE
allow "extras" params in config

### PR DESCRIPTION
**Pull request by netfarma**
Hi.
this is my first PR.
I hope I didn't damege anything :)

### CODE REVIEW

**Comment by jbouzekri** [comment]
I have reviewed it. I think you are missing the build of the menu item. You have correctly added the extra params to the definition file but you don't use it when building the menu : 

https://github.com/jbouzekri/ConfigKnpMenuBundle/blob/master/Provider/ConfigurationMenuProvider.php#L143

**Comment by exchentrix** [comment]
Hey, can you please merge this pull request? I also need the extra params.

**Comment by jbouzekri** [comment]
My bad I did not receive any notification when you pushed the new commit. Il will merge this today.

**Comment by jbouzekri** [comment]
See comment #11

**Pull request closed without merging**
